name: Build VoltageOS ROM (sky)

on:
  workflow_dispatch:  # run manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 360
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git-core repo openjdk-11-jdk bc bison build-essential \
            curl zip unzip python3 python-is-python3 ccache

      - name: Install repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "PATH=\$PATH:~/bin" >> ~/.bashrc
          source ~/.bashrc

      - name: Initialize VoltageOS manifest
        run: |
          mkdir -p android && cd android
          repo init -u https://github.com/VoltageOS/manifest.git -b 14
          repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune -j2

      - name: Clone device sources
        run: |
          cd android
          git clone https://github.com/daveshbackup/device_xiaomi_sky.git device/xiaomi/sky
          # Agar vendor/kernel repos hain to unhe yahan add kar:
          # git clone https://github.com/daveshbackup/vendor_xiaomi_sky.git vendor/xiaomi/sky
          # git clone https://github.com/daveshbackup/kernel_xiaomi_sky.git kernel/xiaomi/sky

      - name: Setup build environment
        run: |
          cd android
          source build/envsetup.sh
          export USE_CCACHE=1
          export CCACHE_DIR=~/.ccache
          ccache -M 50G
          git config --global user.email "you@example.com"
          git config --global user.name "builder"

      - name: Build ROM
        run: |
          cd android
          lunch voltage_sky-userdebug
          mka bacon -j$(nproc) || (tail -n 200 out/*/last_log.txt || true; exit 1)

      - name: Upload ROM zip
        uses: actions/upload-artifact@v4
        with:
          name: voltageos-sky
          path: android/out/target/product/sky/*.zip
